package com.apps.freeroadingdriver.eventbus;



public interface EventConstant {
    int NETWORK_ERROR = -1;
    int TOKEN_EXPIRE = 0;
    int PROMO_CALL_BACK = 00;
    int LOGIN_SUCCESS = 1;
    int FORGOT_PASSWORD_SUCCESS = 2;
    int VERIFY_OTP_SUCCESS = 3;
    int RESET_PASSWORD_SUCCESS = 4;
    int LOGIN_ERROR = 5;
    int FORGOT_PASSWORD_ERROR = 6;
    int VERIFY_OTP_ERROR = 7;
    int RESET_PASSWORD_ERROR = 8;
    int SIGN_UP_SUCCESS = 9;
    int SIGN_UP_ERROR = 10;
    int LOGOUT_SUCCESS = 11;
    int LOGOUT_ERROR = 12;

    int CANCEL_SUCCESS = 13;
    int CANCEL_ERROR = 14;

    int CANCEL = 113;


    int MOBILE_VERIFICATION_SUCCESS = 15;
    int MOBILE_VERIFICATION_ERROR = 16;

    int EDIT_PROFILE_SUCESS = 17;
    int EDIT_PROFILE_ERROR = 18;

    int BEGIN_JOURNEY_SUCCESS = 19;
    int BEGIN_JOURNEY_ERROR = 20;

    int PAGES_SUCESS = 21;
    int PAGE_ERROR = 22;

    int I_HAVE_ARRIVED_SUCCESS = 23;
    int I_HAVE_ARRIVED_ERROR = 24;

    int RIDE_ACCEPT_SUCCESS = 25;
    int RIDE_ACCEPT_ERROR = 26;

    int RIDE_REJECT_SUCCESS = 27;
    int RIDE_REJECT_ERROR = 28;

    int GET_HOME_DATA_SUCCESS = 29;
    int GET_HOME_DATA_ERROR = 30;

    int GET_RIDE_HISTORY_DETAIL_SUCCESS = 31;
    int GET_RIDE_HISTORY_DETAIL_ERROR = 32;

    int GET_RIDE_HISTORY_SUCCESS = 33;
    int GET_RIDE_HISTORY_ERROR = 34;

    int STATISTICS_SUCCESS = 35;
    int STATISTICS_ERROR = 36;

    int CARDETAILS_SUCCESS = 37;
    int CARDETAILS_ERROR = 38;

    int DROPPED_PASSENGER_SUCCESS = 39;
    int DROPPED_PASSENGER_ERROR = 40;

    int PAYMENT_SUCCESS_STATUS = 41;
    int PAYMENT_ERROR_STATUS = 42;


    int CHANGE_SUCCESS = 43;
    int CHANGE_ERROR = 44;

    int CHANGE_PASSWORD_SUCCESS = 45;
    int CHANGE_PASSWORD_ERROR = 46;

    int EDIT_JOURNEY_SUCCESS = 47;
    int EDIT_JOURNEY_ERROR = 48;

    int REQUESTFORM_SUCCESS = 49;
    int REQUESTFORM_ERROR = 50;

    int ACTIVELIST_SUCCESS = 51;
    int ACTIVELIST_ERROR = 52;

    int CANCELROADTRIP_SUCCESS = 53;
    int CANCELROADTRIP_ERROR = 54;

    int TRIPJOURNEY_SUCCESS = 55;
    int TRIPJOURNEY_ERROR = 56;

    int TRIPEND_SUCCESS = 57;
    int TRIPEND_ERROR = 58;

    int CANCELINDIVIDUAL_SUCCESS = 59;
    int CANCELINDIVIDUAL_ERROR = 60;


    int TRIPSTATUSUPDATE_SUCCESS = 61;
    int TRIPSTATUSUPDATE_ERROR = 62;


    int TRIPINVOICE_SUCCESS = 63;
    int TRIPINVOICE_ERROR = 64;

    int INVOICEPAYAMOUNT_SUCCESS = 65;
    int INVOICEPAYAMOUNT_ERROR = 66;

    int PROFILE_SUCCESS = 69;
    int PROFILE_ERROR = 70;

    int CALL_PASSENGER = 533;

    int LOCATION_UPDATE = 100;
    int STRIPE_UPDATE_SUCCESS = 101;
    int STRIPE_UPDATE_ERROR = 102;
    int STRIPE_HOME_PAGE_UPDATE = 103;
    int CANCEL_INDIVIDUAL_RIDE = 111;
    int I_HAVE_ARRIVED = 114;

    int SERVER_ERROR = 500;

    int MAKE_SUCCESS=116;
    int MAKE_FAILURE=117;

    int MODEL_SUCCESS=118;
    int MODEL_FAILURE=119;

    int VEHICLE_SUCCESS=120;
    int VEHICLE_FAILURE=121;
}
